### ISSUE TITLE
Duration / IPv4 / IPv6 takes very long to appear

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#155]
Viewing log and going back, or "closing" app and coming back will show the Duration / IPv4 / IPv6. It seems the refresh of this page is not triggered in all situations.

![photo_2018-05-04_12-01-55](https://user-images.githubusercontent.com/616885/39622550-f6d535dc-4f92-11e8-8869-0a9ac4c18f8e.jpg)

**Comment by fkooman** [comment]
Switching to "Notifications" and back does not help.

**Comment by fkooman** [comment]
Not sure if you can reproduce this! Close if you can't.

**Comment by dzolnai** [comment]
The cause was that sometimes the VPN library triggered a disconnect status before connecting.
This unsubscribed the status listeners, and so the future statistic updates did not get any new data. 
When coming back to the screen, the listeners were subscribed again, which made it work.
I made sure that the listeners should not be removed on a disconnect status.
