### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [eduvpn/android#157]
Good day ! can i submit a design for your project ?

**Comment by sveeke** [comment]
Sure, we always welcome contributors to the project. We are open to suggestions, but cannot guarantee the inclusion of all artwork that gets submitted. Also please note that everything we do is released under copyleft licenses (AGPLv3 for the code for example) and that the eduVPN foundation must have the full rights of all artwork in order to be able to use it freely.

**Comment by loydjayme25** [comment]
i will modify the current logo to have a better look. if its okay to you my dear PO.

**Comment by loydjayme25** [comment]
![proposals](https://user-images.githubusercontent.com/37318022/39826899-d4b7e724-53e8-11e8-9f81-8f174a81dfd9.png)

**Comment by loydjayme25** [comment]
hello ! i made a design for the project

![proposals](https://user-images.githubusercontent.com/37318022/40887992-9ce719e2-6783-11e8-850d-bf747210b97a.png)
