### ISSUE TITLE
Only contact server(s) when user tries to connect to it

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#187]
Currently all servers are contacted @ application start. This is not ideal as in case (multiple) tokens are revoked the user needs to login to all servers one after the other. 

Simply only contact server when the user tries to connect to it and not before.

**Comment by dzolnai** [comment]
@fkooman this is not a simple change, because we only store the authentication tokens with their server info (logo, base URI, display name) in the app.
When the app starts, we first discover the API if it has not been discovered yet, to get the token and auth endpoints.
Next, we fetch the list of profiles to be displayed to the user.

How would you change this? We do need to refresh the list of profiles sometimes, so app start was the obvious place for it.

**Comment by fkooman** [comment]
1. Show only the (configured) servers on the app landing page, all the information is already available offline in the app itself (no need to contact the network for this)
2. Only contact the network when the user selects the server (fetch profile_list, ...)

I'm not sure how the app currently handles changes in the discovery files? If I remove a server from the discovery file, will it disappear from the app? What if I add or remove a country from the list?

**Comment by fkooman** [comment]
This removes the need for an error dialog as currently implemented. If the token is not valid (anymore) just open the browser directly to start the OAuth flow.

**Comment by dzolnai** [comment]
Fixed, the new version of the app only connects when selecting a server.
