### ISSUE TITLE
ability to delete configurations

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#33]
it seems impossible to delete configurations from the main screen.

**Comment by dzolnai** [comment]
@sveeke @fkooman how should we display it to the user that he/she can delete a configuration?
Add a delete icon? Swipe right/left on the list item? Long press on an item to display a context menu? Something else?

**Comment by sveeke** [comment]
I think swiping can be done by accident, so maybe long press + context menu would be best. What do you think @fkooman ?

**Comment by fkooman** [comment]
I don't have a strong opinion, just follow the convention on Android.

**Comment by sveeke** [comment]
Daniel, do you have (by accident) an example picture or example app (anyone in the app store :) of both the options?

**Comment by dzolnai** [comment]
@sveeke Swipe to delete: Try the official Gmail app, it archives an email when you swipe it.
Long press context menu: Facebook Messenger when you long press on a message,
I can make screenshots if needed.

Swipe might be better in our case, because right now if you press long on a name in the app, it will display its full name (like in Netflix, useful when you have more configs and the app shortens it, and you can't see the differences).

**Comment by fkooman** [comment]
If you accidentally remove a configuration it is not so much of a problem, you can easily re-add it.

**Comment by sveeke** [comment]
In the GMail app, it is really easy to archive an email while you just wanted to scroll in the app, but but when someone deletes it by accident you can just add it again so it's indeed not really a problem. And the long press display full name feature looks usefull so that's another argument for using the swipe feature.

How will this be made clear to users?

**Comment by dzolnai** [comment]
>  it is really easy to archive an email while you just wanted to scroll in the app
Never happened to me, you need to swipe quite much. Also there's an undo button immediately visible after you swiped.

> How will this be made clear to users?
You could display tips somewhere in the app if there's still screen estate left. Although this can be done after 1.0. Most users won't delete a config probably.

**Comment by fkooman** [comment]
True yeah, we should pay attention to not implement too much stuff that is only relevant/used during testing and development. So if the functionality is there that should be enough, people will find it if they look for it!

**Comment by dzolnai** [comment]
Swipe to left to remove.
