### ISSUE TITLE
find a better way to show provider/profile in "connect" screen

### ISSUE THREAD

**Issue by fkooman** [eduvpn/android#47]
Also, if you add custom providers, it is impossible to distinguish between them in the "Connect to VPN" dialog. Probably makes sense to at least show the hostname somewhere there...

**Comment by dzolnai** [comment]
Already fixed.

**Comment by fkooman** [comment]
But how? :) I don't see it...

**Comment by dzolnai** [comment]
It should display the hostname on the latest build. Maybe you need to readd the provider? (swipe to delete)

![screenshot_20161026-204910](https://cloud.githubusercontent.com/assets/3629582/19740111/d1a77142-9bbd-11e6-8b95-1003116a7294.png)

**Comment by fkooman** [comment]
Aha! That's it! Thanks! :) 
Is there something you can do with showing the profile name fully? maybe on the next line?

**Comment by dzolnai** [comment]
You can long press. I can allow 2 lines too.

**Comment by fkooman** [comment]
Maybe @sveeke has some idea about this, or was this also already part of this other UI issue?

**Comment by sveeke** [comment]
I think two lines would be nice. There is quite some information on the line and I think it will never fit on one single line (certainly not when names are getting long). The long press is nice, but is not that intuïtive and clear (and on top of that an extra user action for all listed profiles). So I would say that 2 lines would be best. Maybe something like this:

>[logo] #     Secure Browsing 
[logo] ### uva.eduvpn.nl
[break/line]
[logo] #      Secure Access
[logo] ### uva.eduvpn.nl
[break/line]
[logo] #     USA Endpoint
[logo] ### uva.eduvpn.nl
[break/line]
[logo] #      Secure Browsing
[logo] ### demo.eduvpn.nl
[break/line]

So the profile name is primary important and thus larger than the provider name below it (which I tried to make clear with #'s, since GitHub does not seem to have font size options?). What do you think Daniel?

**Comment by dzolnai** [comment]
New version will have it like this:
![screenshot_20161108-094119](https://cloud.githubusercontent.com/assets/3629582/20092323/cba3f7dc-a597-11e6-81a9-1203af1db78e.png)

**Comment by sveeke** [comment]
Looks nice! I will test it in the new app release.

**Comment by dzolnai** [comment]
I'll mark this as closed, please reopen if still not right.
