### ISSUE TITLE
could not fetch all profiles

### ISSUE THREAD

**Issue by efef** [eduvpn/android#83]
Some users complain that after they disconnect the VPN, they get a "could not fetch all profiles" error. It looks like this issue occurs more often when using 3G/4G. When the error occurs the user can click on the error and choose "retry". Usually the profiles will get loaded.

Requested solution: please retry more often by default to load the profiles before showing the error message

**Comment by fkooman** [comment]
Probably caused by lingering VPN tunnel that's down, but still part of the routing table. Retry could work, or possibly delay a little before requesting after disconnecting, or have a longer time-out before giving up.

**Comment by sveeke** [comment]
This issue is quite bad I think, and even worse: quite inconsistent. Everytime the list with profiles loads, another combination of profiles will be displayed (since not all will be loaded). Couple of screenshots:

No profile could be loaded
![image](https://user-images.githubusercontent.com/12334213/30083215-f03236fc-928d-11e7-9faa-8805af92d6a4.png)

Only Amsterdam could be loaded
![image](https://user-images.githubusercontent.com/12334213/30083241-06090f5a-928e-11e7-9694-f3d8a320e98b.png)

All profiles could be loaded
![image](https://user-images.githubusercontent.com/12334213/30083250-0de804ec-928e-11e7-9a36-c24af04fdbe8.png)

Error message that appears every now and then
![image](https://user-images.githubusercontent.com/12334213/30083258-16f4faae-928e-11e7-9d6b-6b868b52eb67.png)

I also sometimes can see two profiles (Perth and A'dam for example), but not the Institute Access one and Oslo.
